### PR TITLE
Changed the URL schema to support versioned REST API

### PR DESCRIPTION
**Pull request by andriichumak**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-git-workflow-example-fossa-scanning-zuul-el7/3/ : FAILURE in 1m 23s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-git-workflow-example-merge-compliance-check/4/ : SUCCESS in 25s

**Pull request merged**
